const router = require('express').Router();
const {adminAuth} = require('../middleware/middleware')
const {adminLogin} = require('../controllers/adminControllers')
const {getAllEvents,createEvent,updateEvent,getEventById,getEventsByDepartment,getEventsByType,deleteEvent,getstarredEvents,groupEventsByDate,groupEventsByDepartment,groupEventsByType,groupEventsbyDay} = require('../controllers/eventControllers')
const {getAllUsers,createUser,updateUser,getUserById,deleteUser,getuserbyemail,addstarrdeventbyuser,deletestarrdeventbyuser,starredeventsbyuser} = require('../controllers/userControllers') 
const {getAllCrews,createCrew,updateCrew,getCrewById,deleteCrew,getCrewByDepartment,getCrewByRole,groupCrewByDepartment,groupCrewByRole} = require('../controllers/crewControllers')

router.get('/api/admin/login',adminLogin)
router.get('/api/events/all', getAllEvents)
router.get('/api/events/:id', getEventById)
router.get('/api/events/department/:department', getEventsByDepartment)
router.get('/api/events/type/:type', getEventsByType)
router.get('/api/events/all/starred', getstarredEvents)
router.get('/api/events/all/groupbydate', groupEventsByDate)
router.get('/api/events/all/groupbydepartment', groupEventsByDepartment)
router.get('/api/events/all/groupbytype', groupEventsByType)
router.get('/api/events/all/groupbyday', groupEventsbyDay)
router.post('/api/events/create', adminAuth, createEvent)
router.put('/api/events/update/:id', adminAuth, updateEvent)
router.delete('/api/events/delete/:id', adminAuth, deleteEvent)
router.get('/api/crews/all', getAllCrews)
router.get('/api/crews/:id', getCrewById)
router.post('/api/crews/create', adminAuth, createCrew)
router.put('/api/crews/update/:id', adminAuth, updateCrew)
router.delete('/api/crews/delete/:id', adminAuth, deleteCrew)
router.get('/api/crews/department/:department', getCrewByDepartment)
router.get('/api/crews/role/:role', getCrewByRole)
router.get('/api/crews/all/groupbydepartment', groupCrewByDepartment)
router.get('/api/crews/all/groupbyrole', groupCrewByRole)
router.get('/api/users/all', getAllUsers)
router.get('/api/users/:id', getUserById)
router.get('/api/users/email/:email', getuserbyemail)
router.post('/api/users/create', adminAuth, createUser)
router.put('/api/users/update/:id', adminAuth, updateUser)
router.delete('/api/users/delete/:id', adminAuth, deleteUser)


module.exports = router;